=== ukhsa-collaboration/gpha-mscape-hcid-refs/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "array",
    "items": {
        "type": "object",
        "required": [
            "name",
            "taxon_id",
            "min_count",
            "required_refs",
            "min_coverage",
            "additional_refs"
        ],
        "properties": {
            "name": {
                "type": "string",
                "minLength": 1
            },
            "taxon_id": {
                "type": "integer",
                "minimum": 1
            },
            "alt_taxon_id": {
                "type": "array",
                "items": {
                    "type": "integer",
                    "minimum": 1
                },
                "minItems": 1,
                "uniqueItems": true
            },
            "min_count": {
                "type": "integer",
                "minimum": 0
            },
            "required_refs": {
                "type": "array",
                "items": {
                    "type": "string",
                    "pattern": "^[A-Z]{1,3}_?[0-9]+\\.[1-9]$"
                },
                "minItems": 1,
                "uniqueItems": true
            },
            "min_coverage": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
            },
            "additional_refs": {
                "type": "array",
                "items": {
                    "type": "string",
                    "pattern": "^[A-Z]{1,3}_?[0-9]+\\.[1-9]$"
                },
                "uniqueItems": true
            }
        },
        "additionalProperties": false,
        "allOf": [
            {
                "if": {
                    "required": [
                        "alt_taxon_id"
                    ]
                },
                "then": {
                    "properties": {
                        "alt_taxon_id": {
                            "minItems": 1
                        }
                    }
                }
            }
        ]
    }
}

=== ukhsa-collaboration/gpha-mscape-hcid-refs/hcid.json
[
        {
                "name": "Argentine haemorrhagic fever (Junin virus)",
                "taxon_id": 2169991,
                "min_count": 1,
                "required_refs": [
                        "NC_005080.1",
                        "NC_005081.1"
                ],
                "min_coverage": 0.01,
                "additional_refs": []
        },
        {
                "name": "Andes virus infection (hantavirus)",
                "taxon_id": 1980456,
                "min_count": 1,
                "required_refs": [
                        "NC_003466.1",
                        "NC_003467.2",
                        "NC_003468.2"
                ],
                "min_coverage": 0.01,
                "additional_refs": []
        },
        {
                "name": "Sin Nombre virus infection",
                "taxon_id": 3052499,
                "min_count": 1,
                "required_refs": [
                        "NC_077669.1",
                        "NC_077670.1",
                        "NC_077671.1"
                ],
                "min_coverage": 0.01,
                "additional_refs": []
        },
        {
                "name": "Hantaan virus infection",
                "taxon_id": 3052480,
                "alt_taxon_id": [
                        11602
                ],
                "min_count": 1,
                "required_refs": [
                        "NC_005222.1",
                        "NC_005219.1",
                        "NC_005218.1"
                ],
                "min_coverage": 0.01,
                "additional_refs": []
        },
        {
                "name": "Seoul virus infection",
                "taxon_id": 3052498,
                "alt_taxon_id": [
                        12557
                ],
                "min_count": 1,
                "required_refs": [
                        "NC_005236.1",
                        "NC_005237.1",
                        "NC_005238.1"
                ],
                "min_coverage": 0.01,
                "additional_refs": []
        },
        {
                "name": "Dobrava-Belgrade virus infection (Kurkino virus)",
                "taxon_id": 3052477,
                "alt_taxon_id": [
                        3116880
                ],
                "min_count": 1,
                "required_refs": [
                        "NC_005235.1",
                        "NC_005234.1",
                        "NC_005233.1"
                ],
                "min_coverage": 0.01,
                "additional_refs": []
        },
        {
                "name": "Black Creek Canal virus infection (Orthohantavirus nigrorivense)",
                "taxon_id": 3052490,
                "min_count": 1,
                "required_refs": [
                        "NC_043075.1",
                        "NC_043073.1",
                        "NC_043074.1"
                ],
                "min_coverage": 0.01,
                "additional_refs": []
        },
        {
                "name": "Bayou virus infection",
                "taxon_id": 3052470,
                "alt_taxon_id": [
                        343870
                ],
                "min_count": 1,
                "required_refs": [
                        "NC_038299.1",
                        "NC_038298.1",
                        "NC_038300.1"
                ],
                "min_coverage": 0.01,
                "additional_refs": []
        },
        {
                "name": "Bolivian haemorrhagic fever (Machupo virus)",
                "taxon_id": 3052317,
                "alt_taxon_id": [
                        11628
                ],
                "min_count": 1,
                "required_refs": [
                        "NC_005078.1",
                        "NC_005079.1"
                ],
                "min_coverage": 0.01,
                "additional_refs": []
        },
        {
                "name": "Avian influenza A H7N9",
                "taxon_id": 333278,
                "min_count": 1,
                "required_refs": [
                        "NC_026425.1",
                        "NC_026429.1"
                ],
                "min_coverage": 0.01,
                "additional_refs": [
                        "NC_026422.1",
                        "NC_026423.1",
                        "NC_026424.1",
                        "NC_026426.1",
                        "NC_026427.1",
                        "NC_026428.1"
                ]
        },
        {
                "name": "Avian influenza A H5N1",
                "taxon_id": 102793,
                "min_count": 1,
                "required_refs": [
                        "NC_007362.1",
                        "NC_007361.1"
                ],
                "min_coverage": 0.01,
                "additional_refs": [
                        "NC_007357.1",
                        "NC_007358.1",
                        "NC_007359.1",
                        "NC_007360.1",
                        "NC_007363.1",
                        "NC_007364.1"
                ]
        },
        {
                "name": "Avian influenza A H5N6",
                "taxon_id": 329376,
                "min_count": 1,
                "required_refs": [
                        "KY437783.1",
                        "KY437785.1"
                ],
                "min_coverage": 0.01,
                "additional_refs": [
                        "KY437787.1",
                        "KY437786.1",
                        "KY437784.1",
                        "KY437782.1",
                        "KY437781.1",
                        "KY437780.1"
                ]
        },
        {
                "name": "Avian influenza A H7N7",
                "taxon_id": 119218,
                "min_count": 1,
                "required_refs": [
                        "KT887420.1",
                        "KT887418.1"
                ],
                "min_coverage": 0.01,
                "additional_refs": [
                        "KT887422.1",
                        "KT887421.1",
                        "KT887419.1",
                        "KT887417.1",
                        "KT887416.1",
                        "KT887415.1"
                ]
        },
        {
                "name": "Crimean Congo haemorrhagic fever (CCHF)",
                "taxon_id": 3052518,
                "min_count": 1,
                "required_refs": [
                        "NC_005300.2",
                        "NC_005301.3",
                        "NC_005302.1"
                ],
                "min_coverage": 0.01,
                "additional_refs": []
        },
        {
                "name": "Ebola virus disease (EVD) Orthoebolavirus zairense",
                "taxon_id": 3052462,
                "alt_taxon_id": [
                        1570291
                ],
                "min_count": 1,
                "required_refs": [
                        "NC_002549.1"
                ],
                "min_coverage": 0.01,
                "additional_refs": []
        },
        {
                "name": "Ebola virus disease (EVD) Orthoebolavirus sudanense",
                "taxon_id": 3052460,
                "alt_taxon_id": [
                        186540
                ],
                "min_count": 1,
                "required_refs": [
                        "NC_006432.1"
                ],
                "min_coverage": 0.01,
                "additional_refs": []
        },
        {
                "name": "Ebola virus disease (EVD) Orthoebolavirus taiense",
                "taxon_id": 3052461,
                "alt_taxon_id": [
                        186541
                ],
                "min_count": 1,
                "required_refs": [
                        "NC_014372.1"
                ],
                "min_coverage": 0.01,
                "additional_refs": []
        },
        {
                "name": "Ebola virus disease (EVD) Orthoebolavirus bundibugyoense",
                "taxon_id": 3052458,
                "alt_taxon_id": [
                        565995
                ],
                "min_count": 1,
                "required_refs": [
                        "NC_014373.1"
                ],
                "min_coverage": 0.01,
                "additional_refs": []
        },
        {
                "name": "Lassa fever",
                "taxon_id": 3052310,
                "alt_taxon_id": [
                        11620
                ],
                "min_count": 1,
                "required_refs": [
                        "NC_004296.1",
                        "NC_004297.1"
                ],
                "min_coverage": 0.01,
                "additional_refs": []
        },
        {
                "name": "Lujo virus disease",
                "taxon_id": 3052314,
                "alt_taxon_id": [
                        649188
                ],
                "min_count": 1,
                "required_refs": [
                        "NC_012776.1",
                        "NC_012777.1"
                ],
                "min_coverage": 0.01,
                "additional_refs": []
        },
        {
                "name": "Chapare hemorrhagic fever (CHHF)",
                "taxon_id": 3052302,
                "min_count": 1,
                "required_refs": [
                        "NC_010563.1",
                        "NC_010562.1"
                ],
                "min_coverage": 0.01,
                "additional_refs": []
        },
        {
                "name": "Marburg virus disease (MVD) Orthomarburgvirus marburgense MARV",
                "taxon_id": 1708253,
                "alt_taxon_id": [
                        3052505
                ],
                "min_count": 1,
                "required_refs": [
                        "NC_001608.3"
                ],
                "min_coverage": 0.01,
